dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'
dotenv: .env
dev_deployment_artifacts: True
networks:
  development:
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
  rinkeby:
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    vrf_coordinator_subscription_id: 10572
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
